apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-0kqe78
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-0kqe78
  namespace: my-nginx-0kqe78
  labels:
    name: nginx-0kqe78
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-0kqe78
  template:
    metadata:
      namespace: my-nginx-0kqe78
      labels:
        name: nginx-0kqe78
    spec:
      containers:
      - name: nginx-0kqe78
        image: nginx
        ports:
        - containerPort: 80

